### ISSUE TITLE
Tasks Calendar Wrapper appears to be updating frequently, not sure why

### ISSUE THREAD

**Issue by miaoziguan** [Leonezz/obsidian-tasks-calendar-wrapper#115]
Tasks Calendar Wrapper appears to be updating frequently, not sure why

**Comment by Leonezz** [comment]
Hi @miaoziguan I am not sure what do you mean by updating?

**Comment by miaoziguan** [comment]
Will keep popping up in my plugin update list

zhuwenq ***@***.***> 于2024年5月7日周二 09:44写道：

**Comment by miaoziguan** [comment]
And the version number hasn't changed.

扑克 ***@***.***> 于2024年5月7日周二 09:49写道：

**Comment by Leonezz** [comment]
Oh that is because in the last release I mistakenly used the old version number to run the workflow, it should be fixed now

**Comment by Suyashtnt** [comment]
I still have this issue. IIRC you have to publish a brand new version if you make this mistake. It's happened to me with another plugin before
